# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWiki2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_wiki2(self):
    # Test name: wiki2
    # Step # | name | target | value
    # 1 | open | https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal | 
    self.driver.get("https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal")
    # 2 | setWindowSize | 976x816 | 
    self.driver.set_window_size(976, 816)
    # 3 | click | linkText=Rechercher | 
    self.driver.find_element(By.LINK_TEXT, "Rechercher").click()
    # 4 | click | name=search | 
    self.driver.find_element(By.NAME, "search").click()
    # 5 | type | name=search | Elon Musk
    self.driver.find_element(By.NAME, "search").send_keys("Elon Musk")
    # 6 | sendKeys | name=search | ${KEY_ENTER}
    self.driver.find_element(By.NAME, "search").send_keys(Keys.ENTER)
    # 7 | storeText | css=.mw-page-title-main | abou
    self.vars["abou"] = self.driver.find_element(By.CSS_SELECTOR, ".mw-page-title-main").text
    # 8 | store | Elon Musk | me
    self.vars["me"] = "Elon Musk"
    # 9 | assert | me | ${abou}
    assert self.vars["me"] == self.vars['abou']
  
